name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4  # Use the latest stable version
      
    - name: Debug Workspace
      run: ls -R  # Inspect workspace to verify file structure

    - name: Executing Shell Script
      run: |
        if [ -f "./ascii-script.sh" ]; then
          chmod +x ascii-script.sh
          ./ascii-script.sh
        else
          echo "ascii-script.sh not found. Debugging workspace..."
          ls -ltra  # Show all files in the current directory
          exit 1
        fi
